import { Geist, Geist_Mono, Tiro_Bangla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { FavoriteProvider } from "@/context/FavoriteContext";
import { CartProvider } from "@/context/CartContext";
import CartDrawer from "@/components/CartDrawer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tiroBangla = Tiro_Bangla({
  weight: ['400'],
  subsets: ['bengali'],
  variable: '--font-tiro-bangla',
});

export const metadata = {
  title: "Glace Dream House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tiroBangla.variable} antialiased`}
      >
        <FavoriteProvider>
          <CartProvider>
            <Navbar></Navbar>
            {children}
            <CartDrawer />
          </CartProvider>
        </FavoriteProvider>
      </body>
    </html>
  );
}
